version: 0.0
os: linux
files:
  - source: /
    destination: /app/current
    overwrite: true
permissions:
  - object: /app/current
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 6000
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300