version: 0.0
os: linux
files:
  - source: /
    destination: /app/current
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
#   AfterInstall:
#     - location: scripts/after_install.sh
#       timeout: 6000
#       runas: root
#   ApplicationStart:
#     - location: scripts/application_start.sh
#       timeout: 6000
#       runas: root
#   ApplicationStop:
#     - location: scripts/application_stop.sh
#       timeout: 300
#       runas: root