version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/current
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 6000
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root