version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./apps/nx-express/Dockerfile
    volumes:
      - .app
    command: docker run -p 3000:3000 -t nx-express-web
    ports:
      - "8080:8080"